# Generated by Django 4.1.1 on 2024-05-03 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_beneficios_dashboard'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beneficios_dashboard',
            options={'verbose_name': 'Beneficios dashboard'},
        ),
    ]
